version: '3'
services:
  mqtt_server:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mqtt/mapped_dir/config/:/mosquitto/config/:ro
      - ./mqtt/mapped_dir/log:/mosquitto/log/
      - ./mqtt/mapped_dir/data:/mosquitto/data/
  homeassistant:
    build: .
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./hassconfig/:/config
    environment:
      - TZ=Europe/Paris
      - DISABLE_JEMALLOC=false
    restart: always
    ports:
      - 8123:8123
    depends_on:
      - "mqtt_server"
