homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.7926
  longitude: 7.3349
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 231
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  server_port: 8123
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: debug
  logs:
    homeassistant.components.mqtt: debug

mqtt:
  broker: localhost
  port: 1883
  client_id: hass
  username:
  password:
  discovery: true
  discovery_prefix: homeassistant


# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: random
  - platform: mqtt
    name: 'Room Humidity'
    state_topic: 'room/humidity'
  - platform: mqtt
    state_topic: 'mysensors-out/122/1/1/0/0'
    name: 'Temperature'
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: 'mysensors-out/122/0/1/0/1'
    name: 'Humidity'
    unit_of_measurement: '%'

binary_sensor:
  - platform: mqtt
    state_topic: "mysensors-out/99/1/1/0/2"
    payload_on: 1
    payload_off: 0

switch:
  - platform: mqtt
    command_topic: "mysensors-in/99/1/1/1/2"
    payload_on: 1
    payload_off: 0

switch2:
  - platform: mqtt
    name: "Bedroom Switch"
    command_topic: "homeassistant/bedroom/switch1/set"
    state_topic: "homeassistant/bedroom/switch1/set"
    availability_topic: "homeassistant/bedroom/switch1/availability"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 0
    retain: true

light:
  - platform: mqtt
    name: "Bedroom Light"
    command_topic: "homeassistant/bedroom/light1/set"
    state_topic: "homeassistant/bedroom/light1/set"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true

mysensors:
  gateways:
    - device: mqtt
      topic_in_prefix: 'mysensors-out'
      topic_out_prefix: 'mysensors-in'
  version: 2.0


device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true
    mqtt_topic: "owntracks/#"

# Text to speech
tts:
  - platform: google_translate

#group: !include groups.yaml
#automation: !include automations.yaml